
package co.com.bancoabc.notificarclientesbancoabc;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "NotificarClientesBancoABCSOAP", serviceName = "NotificarClientesBancoABC", targetNamespace = "http://www.bancoABC.com.co/NotificarClientesBancoABC/", wsdlLocation = "/wsdls/NotificarClientesBancoABC.wsdl", endpointInterface = "co.com.bancoabc.notificarclientesbancoabc.NotificarClientesBancoABC")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class NotificarClientesBancoABC_NotificarClientesBancoABCSOAPImpl implements NotificarClientesBancoABC {

	public NotificarClientesBancoABC_NotificarClientesBancoABCSOAPImpl() {
	}

	/**
	 * 
	 * @param direccionNotificacion
	 * @param tipoID
	 * @param numID
	 * @param tipoNotificacion
	 * @return returns boolean
	 */
	public boolean notificarClientes(String tipoID, String numID, String tipoNotificacion,
			String direccionNotificacion) {
		// replace with your impl here
		return true;
	}

}
