
package co.com.bancoabc.consultarsaldobancoabc;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "ConsultarSaldoBancoABCSOAP", serviceName = "ConsultarSaldoBancoABC", targetNamespace = "http://www.bancoABC.com.co/ConsultarSaldoBancoABC/", wsdlLocation = "/wsdls/ConsultarSaldoBancoABC.wsdl", endpointInterface = "co.com.bancoabc.consultarsaldobancoabc.ConsultarSaldoBancoABC")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ConsultarSaldoBancoABC_ConsultarSaldoBancoABCSOAPImpl implements ConsultarSaldoBancoABC {

	public ConsultarSaldoBancoABC_ConsultarSaldoBancoABCSOAPImpl() {
	}

	/**
	 * 
	 * @param tipoID
	 * @param numID
	 * @return returns double
	 */
	public double consultarSaldo(String tipoID, String numID) {
		return Math.floor(Math.random() * 2000000);
	}

}
