
package co.com.bancoabc.gestionarconveniosbancoabc;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "GestionarConveniosBancoABCSOAP", serviceName = "GestionarConveniosBancoABC", targetNamespace = "http://www.bancoABC.com.co/GestionarConveniosBancoABC/", wsdlLocation = "/wsdls/GestionarConveniosBancoABC.wsdl", endpointInterface = "co.com.bancoabc.gestionarconveniosbancoabc.GestionarConveniosBancoABC")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class GestionarConveniosBancoABC_GestionarConveniosBancoABCSOAPImpl implements GestionarConveniosBancoABC {

	public GestionarConveniosBancoABC_GestionarConveniosBancoABCSOAPImpl() {
	}

	String convenios = "Gas la venosa;ETB;Acueducto;Luz CRM";

	/**
	 * 
	 * @param nomConvenio
	 * @param endPointConvenio
	 * @param descConvenio
	 * @return returns boolean
	 */
	public boolean agregarConvenio(String nomConvenio, String descConvenio, String endPointConvenio) {
		// replace with your impl here
		convenios += nomConvenio;
		return true;
	}

	/**
	 * 
	 * @param idUsuario
	 * @return returns java.lang.String
	 */
	public String consultarConvenios(String idUsuario) {
		// replace with your impl here
		return convenios;
	}

	/**
	 * 
	 * @param nomConvenio
	 * @return returns boolean
	 */
	public boolean eliminarConvenio(String nomConvenio) {
		// replace with your impl here
		convenios = "Gas la venosa;ETB;Acueducto;Luz CRM";
		return true;
	}

}
