
package co.com.bancoabc.validarusuariobancoabc;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "ValidarUsuarioBancoABCSOAP", serviceName = "ValidarUsuarioBancoABC", targetNamespace = "http://www.bancoABC.com.co/ValidarUsuarioBancoABC/", wsdlLocation = "/wsdls/ValidarUsuarioBancoABC.wsdl", endpointInterface = "co.com.bancoabc.validarusuariobancoabc.ValidarUsuarioBancoABC")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class ValidarUsuarioBancoABC_ValidarUsuarioBancoABCSOAPImpl implements ValidarUsuarioBancoABC {

	public ValidarUsuarioBancoABC_ValidarUsuarioBancoABCSOAPImpl() {
	}

	/**
	 * 
	 * @param usuario
	 * @param contrasena
	 * @return returns boolean
	 */
	public boolean validarUsuario(String usuario, String contrasena) {
		// replace with your impl here
		return true;
	}

}
